In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
A = np.array([[3, 1, 0, 0],[1, 2, 0, 1],[0, 0, 1, 1],[0, 1, 1, 1]])
sys = np.linalg.eigh(A)
print(sys[0])
hi = sys[1][:, -1]
print(hi)

[-0.28399787  1.21473855  2.3184589   3.75080042]
[-0.77250966 -0.58000058 -0.08832178 -0.2429556 ]


In [37]:
v = np.random.random(4)
v /= np.sqrt(v@v)

In [44]:
it = 0
delta = 1
while delta > 1e-3:
    v = A@v
    v /= np.sqrt(v@v)
    v *= np.sign(v[0]/hi[0])
    delta = np.linalg.norm(v - hi)
    it += 1
print(v, it)
print(np.dot(A@v, v)/np.dot(v, v))

[-0.77239132 -0.58008038 -0.08843306 -0.2431008 ] 1
3.7508003449390914


In [45]:
lambda_ = 3.5

delta = 1

v = np.random.random(4)
v /= np.sqrt(v@v)

it = 0
while delta > 1e-3:
    v = np.linalg.inv(A - lambda_*np.eye(4)) @ v
    v /= np.sqrt(v@v)
    v *= np.sign(v[0]/hi[0])
    delta = np.linalg.norm(v - hi)
    it += 1
print(v, it)
print(np.dot(A@v, v)/np.dot(v, v))

[-0.77205485 -0.58029952 -0.0887809  -0.24351944] 4
3.750799238861307


In [46]:
lambda_ = 3.7

delta = 1

v = np.random.random(4)
v /= np.sqrt(v@v)

it = 0
while delta > 1e-3:
    v = np.linalg.inv(A - lambda_*np.eye(4)) @ v
    v /= np.sqrt(v@v)
    v *= np.sign(v[0]/hi[0])
    delta = np.linalg.norm(v - hi)
    it += 1
    
print(v, it)
print(np.dot(A@v, v)/np.dot(v, v))

[-0.77254622 -0.57998017 -0.08827828 -0.24290386] 3
3.750800412880113
