In [8]:
import numpy as np

n = 10

l = np.array([
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
])

In [9]:
def L(arr, j):
    rez = 0
    for i in arr[j]:
        rez += i
    return rez

In [11]:
G = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        G[i][j] = l[i][j]/L(l, j)

In [13]:
np.linalg.eigvalsh((G))

array([-1.26079261, -1.12193553, -0.94940926, -0.41189382, -0.30033577,
        0.28919639,  0.43927724,  0.9363002 ,  1.09023105,  1.28936212])

In [25]:
def get_eig_vec(arr, r_0):
    r_old = np.zeros(np.shape(r_0))
    while np.linalg.norm(r_0 - r_old, ord=1) > 1e-4:
        r_old = r_0
        r_0 = (arr @ r_0)
        r_0 /= np.linalg.norm(r_0)
    return r_0

In [26]:
p = get_eig_vec(G, np.ones((10,1)))

In [27]:
G@p

array([[0.14142038],
       [0.14141867],
       [0.28284018],
       [0.42426897],
       [0.28284387],
       [0.14142558],
       [0.42425805],
       [0.56569836],
       [0.28283628],
       [0.14142428]])

In [28]:
p

array([[0.14142318],
       [0.14142501],
       [0.28284698],
       [0.42426115],
       [0.28284303],
       [0.14141761],
       [0.42427285],
       [0.56567468],
       [0.28285116],
       [0.141419  ]])